services:
  app:
    build: .
    image: ftc4:latest
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./uv.lock:/app/uv.lock
      - ~/.cache/uv:/root/.cache/uv
